# Generated by Django 4.0.4 on 2022-05-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.DateField(max_length=15)),
                ('familiya', models.CharField(max_length=15)),
                ('malumot', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('is_active', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('ustozlar', models.ManyToManyField(to='courses.ustoz')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.yonalish')),
            ],
        ),
    ]
