# Generated by Django 4.0.4 on 2022-05-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_fan_ustozlar_alter_fan_yonalish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='ustozlar',
            field=models.ManyToManyField(null=True, to='courses.ustoz'),
        ),
    ]
